### ISSUE TITLE
java.lang.IllegalArgumentException: Unexpected char 0x0a at 31 in authorization value

### ISSUE THREAD

**Issue by mcatta** [LP-Messaging/Android-Messaging-SDK#139]
Hello,
I am opening this issue because we are experiencing several crashes on customers with this stack trace:
```
Fatal Exception: java.lang.IllegalArgumentException: Unexpected char 0x0a at 31 in authorization value
       at okhttp3.Headers$Companion.checkValue(Headers.kt:450)
       at okhttp3.Headers$Companion.access$checkValue(Headers.kt:362)
       at okhttp3.Headers$Builder.add(Headers.kt:261)
       at okhttp3.Request$Builder.addHeader(Request.kt:210)
       at com.liveperson.infra.network.http.HttpHandler$HttpRequestBuilder.build(HttpHandler.java:174)
       at com.liveperson.infra.network.http.HttpHandler.lambda$buildRunnableByType$0(HttpHandler.java:90)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```
The reason is that: LivePerson SDK is calling an API with a token generated from LivePerson backend which contains a forbidden character that doesn't pass the OkHttp's header validation.
```
 at okhttp3.Headers$Companion.checkValue(Headers.kt:450)
```
the header key is `authorization`, looking at the SDK source I found that is used inside the `BadgeCounterRequest`.

We are using the latest SDK version `{ module = "com.liveperson.android:lp_messaging_sdk", version = "5.16.0" }`, could you take a look, please?

If you need other information please let me know.

Marco

**Comment by sruzhytskyi** [comment]
@mcatta Thanks for posting this info. I fixed this issue. I guess, we'd include this fix into 5.19 release.

**Comment by lptle** [comment]
@mcatta 
1. Does it consistently happen? Can you share the steps to reproduce the issue? 
2. What account id are you using? 
3. Does it happen only on v5.16.0?

**Comment by mcatta** [comment]
Hello @lptle ,

I'm sorry but I can't help you anymore because we stopped using LP this September, thank you anyway for your support.

Sincerely,
Marco

**Comment by lptle** [comment]
Thanks @mcatta 
Close this issue.
