### ISSUE TITLE
Fails to initialize after updating Android to 8.1

### ISSUE THREAD

**Issue by bramley-turner-stride** [LP-Messaging/Android-Messaging-SDK#37]
I am getting the following exception in onInitFailed in my app after updating my device to 8.1:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
at android.util.Base64.decode(Base64.java:118)
at com.liveperson.infra.controller.DBEncryptionKeyHelper.setDbEncryptionKey(DBEncryptionKeyHelper.java:251)
at com.liveperson.infra.controller.DBEncryptionKeyHelper.<init>(DBEncryptionKeyHelper.java:125)
at com.liveperson.infra.Infra.initInfra(Infra.java:117)
at com.liveperson.infra.Infra.access$100(Infra.java:29)
at com.liveperson.infra.Infra$InfraInitProcess.init(Infra.java:256)
at com.liveperson.infra.sdkstatemachine.InfraStateMachine$Initializing.visit(InfraStateMachine.java:97)
at com.liveperson.infra.sdkstatemachine.events.InitEvent.accept(InitEvent.java:26)
at com.liveperson.infra.statemachine.BaseStateMachine.apply(BaseStateMachine.java:62)
at com.liveperson.infra.statemachine.BaseStateMachine.changeStateAndPassEvent(BaseStateMachine.java:52)
at com.liveperson.infra.sdkstatemachine.InfraStateMachine$Idle.visit(InfraStateMachine.java:71)
at com.liveperson.infra.sdkstatemachine.events.InitEvent.accept(InitEvent.java:26)
at com.liveperson.infra.statemachine.StateMachineExecutor$RunnableWrapper.run(StateMachineExecutor.java:26)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.os.HandlerThread.run(HandlerThread.java:65)

```

I then can't initialise the chat window - nothing happens because `isValidState()==false`

I don't know if the problem is caused by updating the OS, or maybe due to some crypto changes in API 27?

**Comment by bramley-turner-stride** [comment]
I debugged through the initialization code and found 
in the method `DBEncryptionKeyHelper.decryptKey(String encryptedKey)` :
`PrivateKeyEntry e = (PrivateKeyEntry)this.androidKeyStore.getEntry("androidInfraDbEncKey", (ProtectionParameter)null);`
`e` was `null` so it then crashed at line 
`output.init(2, e.getPrivateKey());`

**Comment by bramley-turner-stride** [comment]
I'm using v2.5.1 (can't update due to #34 )
